export const USE_PROVIDER_KEY_TO_RESET_ATOMS = true;

export enum UserJourney {
  Onboarding = "onboarding",
  Confirmation = "confirmation",
  Portal = "portal",
}

export const US_STATES = [
  { label: "Alabama", value: "AL", inputLabel: "AL" },
  { label: "Alaska", value: "AK", inputLabel: "AK" },
  { label: "Arizona", value: "AZ", inputLabel: "AZ" },
  { label: "Arkansas", value: "AR", inputLabel: "AR" },
  { label: "California", value: "CA", inputLabel: "CA" },
  { label: "Colorado", value: "CO", inputLabel: "CO" },
  { label: "Connecticut", value: "CT", inputLabel: "CT" },
  { label: "Delaware", value: "DE", inputLabel: "DE" },
  { label: "Florida", value: "FL", inputLabel: "FL" },
  { label: "Georgia", value: "GA", inputLabel: "GA" },
  { label: "Hawaii", value: "HI", inputLabel: "HI" },
  { label: "Idaho", value: "ID", inputLabel: "ID" },
  { label: "Illinois", value: "IL", inputLabel: "IL" },
  { label: "Indiana", value: "IN", inputLabel: "IN" },
  { label: "Iowa", value: "IA", inputLabel: "IA" },
  { label: "Kansas", value: "KS", inputLabel: "KS" },
  { label: "Kentucky", value: "KY", inputLabel: "KY" },
  { label: "Louisiana", value: "LA", inputLabel: "LA" },
  { label: "Maine", value: "ME", inputLabel: "ME" },
  { label: "Maryland", value: "MD", inputLabel: "MD" },
  { label: "Massachusetts", value: "MA", inputLabel: "MA" },
  { label: "Michigan", value: "MI", inputLabel: "MI" },
  { label: "Minnesota", value: "MN", inputLabel: "MN" },
  { label: "Mississippi", value: "MS", inputLabel: "MS" },
  { label: "Missouri", value: "MO", inputLabel: "MO" },
  { label: "Montana", value: "MT", inputLabel: "MT" },
  { label: "Nebraska", value: "NE", inputLabel: "NE" },
  { label: "Nevada", value: "NV", inputLabel: "NV" },
  { label: "New Hampshire", value: "NH", inputLabel: "NH" },
  { label: "New Jersey", value: "NJ", inputLabel: "NJ" },
  { label: "New Mexico", value: "NM", inputLabel: "NM" },
  { label: "New York", value: "NY", inputLabel: "NY" },
  { label: "North Carolina", value: "NC", inputLabel: "NC" },
  { label: "North Dakota", value: "ND", inputLabel: "ND" },
  { label: "Ohio", value: "OH", inputLabel: "OH" },
  { label: "Oklahoma", value: "OK", inputLabel: "OK" },
  { label: "Oregon", value: "OR", inputLabel: "OR" },
  { label: "Pennsylvania", value: "PA", inputLabel: "PA" },
  { label: "Rhode Island", value: "RI", inputLabel: "RI" },
  { label: "South Carolina", value: "SC", inputLabel: "SC" },
  { label: "South Dakota", value: "SD", inputLabel: "SD" },
  { label: "Tennessee", value: "TN", inputLabel: "TN" },
  { label: "Texas", value: "TX", inputLabel: "TX" },
  { label: "Utah", value: "UT", inputLabel: "UT" },
  { label: "Vermont", value: "VT", inputLabel: "VT" },
  { label: "Virginia", value: "VA", inputLabel: "VA" },
  { label: "Washington", value: "WA", inputLabel: "WA" },
  { label: "West Virginia", value: "WV", inputLabel: "WV" },
  { label: "Wisconsin", value: "WI", inputLabel: "WI" },
  { label: "Wyoming", value: "WY", inputLabel: "WY" },
];

export const CONDITIONS = [
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "I10",
    display: "Hypertension (High Blood Pressure)",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "E11.9",
    display: "Type 2 Diabetes Mellitus",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "J45.909",
    display: "Asthma",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "E78.5",
    display: "Hyperlipidemia (High Cholesterol)",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "E66.9",
    display: "Obesity",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "M19.90",
    display: "Osteoarthritis",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "J44.9",
    display: "Chronic Obstructive Pulmonary Disease (COPD)",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "F32.9",
    display: "Depression",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "F41.9",
    display: "Anxiety",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "I25.10",
    display: "Coronary Artery Disease (CAD)",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "J30.9",
    display: "Allergic Rhinitis",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "K21.9",
    display: "Gastroesophageal Reflux Disease (GERD)",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "N18.9",
    display: "Chronic Kidney Disease",
  },
  {
    system: "http://hl7.org/fhir/sid/icd-10-cm",
    code: "M54.5",
    display: "Back Pain",
  },
] as const;
